//
// Created by User on 07.11.2018.
//

#ifndef VULKANINITIALIZATIONLIB_VKLOGICALDEVICECREATEINFOPROVIDER_H
#define VULKANINITIALIZATIONLIB_VKLOGICALDEVICECREATEINFOPROVIDER_H


class VkLogicalDeviceCreateInfoProvider {

};


#endif //VULKANINITIALIZATIONLIB_VKLOGICALDEVICECREATEINFOPROVIDER_H
